---
<div align="center">

# Connect-4 [Artificial Intelligence Project]
</div>

---

<div align="center">

## Search Problem 
</div>

A Search Problem is composed by multiple factors:
- States (Any possible configuration of the Board)
- Initial and Goal States
- Action Space (actions and their effects on the environment)
- Action Cost

---

In [1]:
import numpy as np
from copy import (deepcopy)
from os import (system)
import pygame

pygame 2.5.2 (SDL 2.28.3, Python 3.10.0)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
class Connect4:
    # Defining Board's Size
    NROWS = 6
    NCOLS = 7
    
    def __init__(self):
        # Matrix to Store the Board's Values
        self.board = np.zeros(shape=(self.NROWS, self.NCOLS), dtype=np.int8)

        # Array to keep track of the row's index for every column where a piece can be placed
        # Basically it's the Row idx for every column's height
        self.columns_height = np.full(shape=self.NCOLS, fill_value=(self.NROWS - 1), dtype=np.int8)

        # Defining the Possible Actions (Initially a piece can be placed in any column)
        self.actions = set()
        [self.actions.add(col) for col in range(self.NCOLS)]
        
        # Initializing a variable to track the current player
        self.player = 1
        
        # Variable to store the Winner (-1 - Game still running || 0 - Tie || 1 - PLayer 1 || 2 - Player 2 / AI)
        self.winner = - 1

    def move(self, ncol):
        # Creating a new state
        new_state = deepcopy(self)

        # Checks of the given column can be played on
        if(ncol in self.actions):
            # Inserting the move into the board
            new_state.board[new_state.columns_height[ncol]][ncol] = new_state.player
            
            # Updating the "ncol"'s height
            new_state.columns_height[ncol] -= 1
            
            # Checking if the column is full and therefore uncapable of receiving more pieces -> Changes the action space
            if (new_state.columns_height[ncol] < 0):
                new_state.actions.remove(ncol)

            # Updates the current Winner
            new_state.update_winner()
                
            # Updating current player for the next state
            new_state.player = 2 if new_state.player == 1 else 1

        # Returns the New State (Could be the same as the previous if the action could not be performed)
        return new_state

    def update_winner(self):
        # To Implement
        pass
    
    def is_over(self):
        # If the Winner corresponds to -1 then the game is not finished otherwise it is
        return self.winner != -1

    # NEEDS TO BE MODIFIED - WE COULD WRAP THE NEW STATES WITH A TREENODE CLASS - WOULD HELP FOR THE A* AND FOR THE MCTS [ALSO WE COULD USE IT TO SIMPLIFY THE FLOW OF THE GAME - DEPENDING ON THE OPPONENTS]
    def run(self):
        # Creating the Game Loop inside the Terminal
        while not self.is_over():
            system('cls')
            print("\nCURRENT BOARD: \n")
            print(self.board)
            ncol = input(f"\n| Player {self.player} | Choose a Column to Play: ")
            self = self.move(ncol) # Problem Here
            print(self.board)
            break
        
        if self.winner == 0:
            print("Tie")
        else:
            print(f"Player {self.player} Wins!")
    
    def __str__(self):
        CODE = {0:'-', 1:'X', 2:'O'} # Maybe helpfull to convert the board into the same style used in the Assignment 1 Paper
        return str(self.board)

    def __hash__(self):
        return hash(str(self.board))

    def __eq__(self, other:object):
        if (not isinstance(other, Connect4)):
            return False
        return hash(self) == hash(other)
        

In [3]:
game = Connect4()
print(game)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [4]:
game = game.move(1)
game = game.move(1)
game = game.move(1)
game = game.move(1)
game = game.move(1)
game = game.move(1)
game = game.move(1)
print(game.board)

[[0 2 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 1 0 0 0 0 0]]


In [5]:
new_game = Connect4()
new_game.run()


CURRENT BOARD: 

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]



| Player 1 | Choose a Column to Play:  1


[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
Player 1 Wins!


---
<div align="center">

## Graphical User Interface
</div>

---

In [6]:
class GUI:
    # Screen Parameters
    SQSIZE = 80
    X_OFFSET = 60
    Y_OFFSET = 60

    # RGB Colors
    BLACK = (0,0,0)
    WHITE = (255,255,255)
    BLUE = (135,206,250)
    
    def __init__(self):
        self.game = Connect4()
        self.WIDTH = self.game.NCOLS*self.SQSIZE + 2*self.X_OFFSET
        self.HEIGHT = self.game.NROWS*self.SQSIZE + 2*self.Y_OFFSET

    def draw_board(self):
        # To Implement
        pass
    
    def draw(self, screen):
        # Filling the Background with Blue
        screen.fill(self.BLUE)
    
    def run(self):

        # Initializing Window / Screen
        screen = pygame.display.set_mode((self.WIDTH, self.HEIGHT))
        pygame.display.set_caption("Connect-4")

        # Create a Flag to keep track of current state of the Application / GUI
        run = True

        # Main Loop
        while run:

            # Draws the Game Elements into the Screen
            self.draw(screen)
            
            # Event Loop
            for event in pygame.event.get():
                if (event.type == pygame.QUIT):
                    run = False

            # Updates the Window
            pygame.display.update()
        pygame.quit()

In [7]:
App = GUI()

In [8]:
App.run()