---
<div align="center">

# Connect-4 [Artificial Intelligence Project]
</div>

---

<div align="center">

## Search Problem 
</div>

A Search Problem is composed by multiple factors:
- States (Any possible configuration of the Board)
- Initial and Goal States
- Action Space (actions and their effects on the environment)
- Action Cost

---

In [1]:
import numpy as np
from copy import (deepcopy)
import pygame

pygame 2.5.2 (SDL 2.28.3, Python 3.8.0)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
class Connect4:
    # Defining Board's Size
    NROWS = 6
    NCOLS = 7
    
    def __init__(self, board_config=None):
        # Matrix to Store the Board's Values
        self.board = np.zeros(shape=(self.NROWS, self.NCOLS), dtype=np.int8) if board_config is None else board_config

        # Array to keep track of the row's index for every column where a piece can be placed
        # Basically it's the Row idx for every column's height
        self.columns_height = np.full(shape=self.NCOLS, fill_value=(self.NROWS - 1), dtype=np.int8)

        # Defining the Possible Actions (Initially a piece can be placed in any column)
        self.actions = set()
        [self.actions.add(col) for col in range(self.NCOLS)]
        
        # Initializing a variable to track the current player
        self.player = 1
        
        # Variable to store the Winner (-1 - Game still running || 0 - Tie || 1 - PLayer 1 || 2 - Player 2 / AI)
        self.winner = - 1

    def valid_move(self, ncol):
        # Checking if a move can be made (which is basically checking if the collumn is already full)
        return (ncol >= 0 and ncol < self.NCOLS) and (self.board[0][ncol] == 0)

    # --> NEEDS TO BE MODIFIED
    # The move method must return a new instance of the class with the next bord's cfg
    def move(self, ncol, player):
        if (self.valid_move(ncol)):
            # Looping through the column (Bottom -> Up) where we want to insert a piece
            for (nrow, item) in enumerate(self.board[:, ncol][::-1]):
                if (item == 0):
                    self.board[self.NROWS - nrow - 1][ncol] = player
                    return True
        return False

    def is_over(self):
        # To Implement (Check for any 4 piece combination)
        pass

    def run(self):
        # To Implement (Create Main Loop)
        pass
    
    def __str__(self):
        CODE = {0:'-', 1:'X', 2:'O'} # Maybe helpfull to convert the board into the same style as in the Assignment 1 Paper
        return str(self.board)

    def __hash__(self):
        return hash(str(self.board))

    def __eq__(self, other:object):
        if (not isinstance(other, Connect4)):
            return False
        return hash(self) == hash(other)

In [3]:
game = Connect4()
print(game)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [4]:
print(game.columns_height)

[5 5 5 5 5 5 5]


In [5]:
print(game.actions)

{0, 1, 2, 3, 4, 5, 6}


In [6]:
game.move(0, 1)
game.move(2, 1)
game.move(0, 1)
print(game.board)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 1 0 0 0 0]]


---
<div align="center">

## Graphical User Interface
</div>

---

In [7]:
class GUI:
    # Screen Parameters
    SQSIZE = 80
    X_OFFSET = 60
    Y_OFFSET = 60

    # RGB Colors
    BLACK = (0, 0, 0)
    WHITE = (255, 255, 255)
    BLUE = (135,206,250)
    
    def __init__(self):
        self.game = Connect4()
        self.WIDTH = self.game.NCOLS*self.SQSIZE + 2*self.X_OFFSET
        self.HEIGHT = self.game.NROWS*self.SQSIZE + 2*self.Y_OFFSET

    def draw(self, screen):
        screen.fill(self.BLUE)
    
    def run(self):

        # Initialization of the Window / Screen
        screen = pygame.display.set_mode((self.WIDTH, self.HEIGHT))
        pygame.display.set_caption("Connect-4")

        # Create a Flag to keep track of current state of the Application / GUI
        run = True

        # Main Loop
        while run:

            # Draws the Game Elements into the Screen
            self.draw(screen)
            
            # Event Loop
            for event in pygame.event.get():
                if (event.type == pygame.QUIT):
                    run = False

            # Updates the Window
            pygame.display.update()
        pygame.quit()

In [8]:
App = GUI()

In [9]:
App.run()